apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: matching-service-monitor
  namespace: devops
  labels:
    release: prometheus  
spec:
  selector:
    matchLabels:
      app: matching-service
  endpoints:
  - port: http   
    path: /metrics
    interval: 15s