apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service-monitor
  namespace: devops
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - devops
  selector:
    matchLabels:
      app: auth-service
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: matching-service-monitor
  namespace: devops
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - devops
  selector:
    matchLabels:
      app: matching-service
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: recovery-case-service-monitor
  namespace: devops
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - devops
  selector:
    matchLabels:
      app: recovery-case-service
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
