version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/auth-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/recovery-case-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"