apiVersion: v1
kind: ConfigMap
metadata:
  name: matching-postgres-config
  namespace: devops
data:
  POSTGRES_DB: "matching_service"
  POSTGRES_HOST: "matching-postgres-service"
  POSTGRES_PORT: "5432"