global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

<<<<<<< HEAD
<<<<<<< HEAD
  - job_name: matching-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - matching-service:8000
=======
  - job_name: item-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - item-service:8000
>>>>>>> b6b33ef (feat: pipeline and observability)
=======
  - job_name: matching-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - matching-service:8000
>>>>>>> 2133565 (fix: pipeline matching-service)
