apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: item-postgres
  namespace: devops
spec:
  serviceName: "item-postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: item-postgres
  template:
    metadata:
      labels:
        app: item-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: item-postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: item-postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: item-postgres-config
              key: POSTGRES_DB
        volumeMounts:
        - name: item-postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: item-postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi