apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: recovery-postgres
  namespace: devops
spec:
  serviceName: "recovery-postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: recovery-postgres
  template:
    metadata:
      labels:
        app: recovery-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: recovery-postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: recovery-postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: recovery-postgres-config
              key: POSTGRES_DB
        volumeMounts:
        - name: recovery-postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: recovery-postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi